

services:      

  db: 
    image: postgres:15  
    container_name: postgres-banco 
    environment:
      POSTGRES_DB: task-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data  # Salva os dados para não perder quando parar o container

volumes:
  pgdata:  # Volume para guardar os dados do banco de forma permanente
  
  
  
## comando para subir imagem do postgres
## docker-compose up -d
## by Lucaasshq
