version: "3.8"  # Versão do docker-compose

services:       # Lista dos serviços que vão rodar

  db: # Serviço do banco de dados
    image: postgres:15  # Usa o PostgreSQL versão 15
    container_name: postgres-banco  # Nome do container do banco
    environment: # Configura o banco com usuário, senha e nome do banco
      POSTGRES_DB: task-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"  # Liga a porta 5432 do container com a do computador
    volumes:
      - pgdata:/var/lib/postgresql/data  # Salva os dados para não perder quando parar o container

volumes:
  pgdata:  # Volume para guardar os dados do banco de forma permanente
  
  
  
  ## comando para subir imagem do postgres
## docker compose up -d